<?php


namespace tests;


use PHPUnit\Framework\TestCase;
use services\Router;

class RouterTest extends TestCase
{
    private $my;

    public function setUp()
    {
        @session_start();
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->my = new Router();
    }

    public function testGetController()
    {
        $this->assertEquals('\controllers\CatalogController', $this->my->getController());
        $this->assertNotNull($this->my->getController());
    }

    public function testGetMethod()
    {
        $this->assertEquals('\model\CatalogModel', $this->my->getModel());
        $this->assertNotNull($this->my->getController());
    }
}